$('.epaule').click(function(){
$('.epauletxt').toggle();
$('poignettxt').hide();
$('hanchetxt').hide();
$('coudetxt').hide();
$('chevilletxt').hide();
$('genoutxt').hide();
})

$('.poignet').click(function(){
$('.poignettxt').toggle();
$('epauletxt').hide();
$('hanchetxt').hide();
$('coudetxt').hide();
$('chevilletxt').hide();
$('genoutxt').hide();
})

$('.hanche').click(function(){
$('.hanchetxt').toggle();
$('poignettxt').hide();
$('epauletxt').hide();
$('coudetxt').hide();
$('chevilletxt').hide();
$('genoutxt').hide();
})
$('.coude').click(function(){
$('.coudetxt').toggle();
$('poignettxt').hide();
$('hanchetxt').hide();
$('epauletxt').hide();
$('chevilletxt').hide();
$('genoutxt').hide();
})
$('.cheville').click(function(){
$('.chevilletxt').toggle();
$('poignettxt').hide();
$('epauletxt').hide();
$('coudetxt').hide();
$('chevilletxt').hide();
$('genoutxt').hide();
})
$('.genou').click(function(){
$('.genoutxt').toggle();
$('poignettxt').hide();
$('hanchetxt').hide();
$('coudetxt').hide();
$('chevilletxt').hide();
$('epauletxt').hide();
})
